### ISSUE TITLE
DoTweenの導入の申し入れ

### ISSUE THREAD

**Issue by YuFukai201** [TECH-C-school/BIGBEAR#1]
AssetStore
https://www.assetstore.unity3d.com/jp/#!/content/27676

使いやすいので導入のご検討をお願いします。

**Comment by riverreal** [comment]
同意

**Comment by ryoya0914** [comment]
同意します。

**Comment by tks2shimizu** [comment]
@YuFukai201 
masterからブランチを分けて、DoTweenをインストールし、プルリクエストを送ってください。

**Comment by tks2shimizu** [comment]
@YuFukai201 
ありがとうございます。マージ完了しました。
10/26(木)に再度皆さんに連絡しますが、各ブランチにてmasterブランチをマージしてください。

**Comment by YuFukai201** [comment]
@tks2shimizu
ありがとうございます。
