### ISSUE TITLE
設定について

### ISSUE THREAD

**Issue by afresgamer** [TECH-C-school/BIGBEAR#4]
・難易度はシーン切り替えたら、ゲーム難易度を選択してからメインゲームにいってリザルト画面に行く流れですか？
・サイズ指定ってありますか(例えば、1024＊768みたいな感じです)？
・爆弾は地面にあったら、消えるのかすり抜けますか？
・物資も地面にあったら、消えるのかすり抜けますか？
・リザルト画面ってUIがないのですが、どうやって作りますか？

**Comment by tks2shimizu** [comment]
リザルト画面は共通で用意するので不要です。

**Comment by Soraharada** [comment]
原田と申します、よろしくお願いいたします。

清水さんからは『詳細な仕様は学生が考える』ということを伺っておりますので、
仕様等に関してはゲームの考え方やヒントを提示いたします。

まず、1つ目の質問
『難易度はシーン切り替えたら、ゲーム難易度を選択してからメインゲームにいってリザルト画面に行く流れですか？』
に関しては全体設計の問題となりますので清水さんにご確認ください。

2つ目の質問
『サイズ指定ってありますか(例えば、1024＊768みたいな感じです)？』
に関しては、スマートフォンを想定した1136x640（iphone5s）にて素材を作成しております。
ですが本ゲームアプリはマルチプラットフォーム展開を行うということを伺っておりますので、
比率が変わった際には下駄を履かせる（シネマ風の黒帯）などの処置が必要となるかと思われます。

3つ目と4つ目の質問
『爆弾は地面にあったら、消えるのかすり抜けますか？』
『物資も地面にあったら、消えるのかすり抜けますか？』
に関してお答えします。

本ゲームはキャッチをするというゲームですので、爆弾や物資は落ちて消えるというのが定石かと思われます。
ですが、物資に限って言えば落ちても消えないという試みも面白いかと思われますが、
その際は「落ちた物資を爆弾を避けながら回収するゲーム」へとゲーム性が変化しますのでご注意ください。
afresgamerさんの考えで設定していただければOKです。

最後の質問
『リザルト画面ってUIがないのですが、どうやって作りますか？』
に関しては清水さんが答えているので割愛いたします。

以上。
よろしくお願いいたします。
