### ISSUE TITLE
Game_02仕様についての質問

### ISSUE THREAD

**Issue by YuFukai201** [TECH-C-school/BIGBEAR#5]
・弾は飛距離に応じて時間差で着弾すると書かれていますが、ビルなどの素材を見る限り奥行きが
　 無いように見えるのですが、弾の飛距離は全て一定という認識でよろしいでしょうか？

**Comment by Soraharada** [comment]
原田と申します、よろしくお願いいたします。
さて、スナイプゲームに関しての質問ということでよろしいでしょうか。

風による弾道変化などの処理がありますので、
弾の飛距離は全て一定で、奥行きが存在しない方が実装が簡単である考えておりました。
もしYuFukai201さんが、より難易度が高い実装をお望みでしたら新しい背景をご用意いたします。
その際はご一報ください。

以上です。
よろしくお願いいたします。

**Comment by YuFukai201** [comment]
飛距離が一定で、奥行きがないということで承知致しました。
難易度に関してはシステムができてからまた改めて考えようと思っています。

お忙しい中、ご返答ありがとうございました。
